export const GET_ACCOUNTLIST_REQUEST  = 'GET_ACCOUNTLIST_REQUEST';
export const GET_ACCOUNTLIST_SUCCESS  = 'GET_ACCOUNTLIST_SUCCESS';
export const GET_ACCOUNTLIST_FAILURE  = 'GET_ACCOUNTLIST_FAILURE';
