export const TOGGLE_BUDGET_SELECTOR  = 'TOGGLE_BUDGET_SELECTOR';

export const GET_BUDGETLIST_REQUEST  = 'GET_BUDGETLIST_REQUEST';
export const GET_BUDGETLIST_SUCCESS  = 'GET_BUDGETLIST_SUCCESS';
export const GET_BUDGETLIST_FAILURE  = 'GET_BUDGETLIST_FAILURE';

export const SET_NEWBUDGET_BEGIN = 'SET_NEWBUDGET_BEGIN';
export const SET_NEWBUDGET_END = 'SET_NEWBUDGET_END';
