export const SET_CURRENT_BUDGET  = 'SET_CURRENT_BUDGET';

export const GET_BUDGETENTRYLIST_REQUEST  = 'GET_BUDGETENTRYLIST_REQUEST';
export const GET_BUDGETENTRYLIST_SUCCESS  = 'GET_BUDGETENTRYLIST_SUCCESS';
export const GET_BUDGETENTRYLIST_FAILURE  = 'GET_BUDGETENTRYLIST_FAILURE';

export const BUDGETENTRY_PARTIAL_UPDATE = 'BUDGETENTRY_PARTIAL_UPDATE';
export const BUDGETENTRY_PARTIAL_SUCCESS = 'BUDGETENTRY_PARTIAL_SUCCESS';
