export const TOGGLE_HIDDEN_ENTRIES = 'TOGGLE_HIDDEN_ENTRIES';

export const GET_BUDGETLIST_REQUEST  = 'GET_BUDGETLIST_REQUEST';
export const GET_BUDGETLIST_SUCCESS  = 'GET_BUDGETLIST_SUCCESS';
export const GET_BUDGETLIST_FAILURE  = 'GET_BUDGETLIST_FAILURE';
