export const GET_CATEGORYLIST_REQUEST  = 'GET_CATEGORYLIST_REQUEST';
export const GET_CATEGORYLIST_SUCCESS  = 'GET_CATEGORYLIST_SUCCESS';
export const GET_CATEGORYLIST_FAILURE  = 'GET_CATEGORYLIST_FAILURE';
