export const GET_CURRENCYLIST_REQUEST  = 'GET_CURRENCYLIST_REQUEST';
export const GET_CURRENCYLIST_SUCCESS  = 'GET_CURRENCYLIST_SUCCESS';
export const GET_CURRENCYLIST_FAILURE  = 'GET_CURRENCYLIST_FAILURE';
