export const GET_TOTALSREPORT_REQUEST  = 'GET_TOTALSREPORT_REQUEST';
export const GET_TOTALSREPORT_SUCCESS  = 'GET_TOTALSREPORT_SUCCESS';
export const GET_TOTALSREPORT_FAILURE  = 'GET_TOTALSREPORT_FAILURE';

export const GET_SIMPLEASSETREPORT_REQUEST  = 'GET_SIMPLEASSETREPORT_REQUEST';
export const GET_SIMPLEASSETREPORT_SUCCESS  = 'GET_SIMPLEASSETREPORT_SUCCESS';
export const GET_SIMPLEASSETREPORT_FAILURE  = 'GET_SIMPLEASSETREPORT_FAILURE';

export const SET_REPORT_STARTDATE = 'SET_REPORT_STARTDATE'
export const SET_REPORT_ENDDATE = 'SET_REPORT_ENDDATE'
export const SET_REPORT_GRANULARITY = 'SET_REPORT_GRANULARITY'
