export const GET_TOTALSREPORT_REQUEST  = 'GET_TOTALSREPORT_REQUEST';
export const GET_TOTALSREPORT_SUCCESS  = 'GET_TOTALSREPORT_SUCCESS';
export const GET_TOTALSREPORT_FAILURE  = 'GET_TOTALSREPORT_FAILURE';
