export const GET_TRANSACTIONLIST_REQUEST  = 'GET_TRANSACTIONLIST_REQUEST';
export const GET_TRANSACTIONLIST_SUCCESS  = 'GET_TRANSACTIONLIST_SUCCESS';
export const GET_TRANSACTIONLIST_NODATA  = 'GET_TRANSACTIONLIST_NODATA';
export const GET_TRANSACTIONLIST_FAILURE  = 'GET_TRANSACTIONLIST_FAILURE';

export const SET_TRANSACTION_PAGESIZE = 'SET_TRANSACTION_PAGESIZE';
export const GET_TRANSACTION_NEXTPAGE = 'GET_TRANSACTION_NEXTPAGE';
