export const GET_TRANSACTIONLIST_REQUEST  = 'GET_TRANSACTIONLIST_REQUEST';
export const GET_TRANSACTIONLIST_SUCCESS  = 'GET_TRANSACTIONLIST_SUCCESS';
export const GET_TRANSACTIONLIST_FAILURE  = 'GET_TRANSACTIONLIST_FAILURE';
