export const GET_TRANSACTIONLIST_REQUEST  = 'GET_TRANSACTIONLIST_REQUEST';
export const GET_TRANSACTIONLIST_SUCCESS  = 'GET_TRANSACTIONLIST_SUCCESS';
export const GET_TRANSACTIONLIST_NODATA  = 'GET_TRANSACTIONLIST_NODATA';
export const GET_TRANSACTIONLIST_FAILURE  = 'GET_TRANSACTIONLIST_FAILURE';

export const SET_TRANSACTION_PAGESIZE = 'SET_TRANSACTION_PAGESIZE';
export const GET_TRANSACTION_NEXTPAGE = 'GET_TRANSACTION_NEXTPAGE';

export const SET_TRANSACTION_VIEW_PERIOD = 'SET_TRANSACTION_VIEW_PERIOD';
export const SET_TRANSACTION_VIEW_BEGINNING = 'SET_TRANSACTION_VIEW_BEGINNING';
export const SET_TRANSACTION_VIEW_END = 'SET_TRANSACTION_VIEW_END';

export const SET_TRANSACTION_FILTER_ACCOUNT = 'SET_TRANSACTION_FILTER_ACCOUNT';
export const SET_TRANSACTION_FILTER_TAG = 'SET_TRANSACTION_FILTER_TAG';
export const SET_TRANSACTION_FILTER_COMMENT = 'SET_TRANSACTION_FILTER_COMMENT';

export const APPLY_TRANSACTION_FILTER = 'SET_TRANSACTION_FILTER_APPLY';
export const CLEAR_TRANSACTION_FILTER = 'SET_TRANSACTION_FILTER_CLEAR';

export const DELETE_TRANSACTION_REQUEST = 'DELETE_TRANSACTION_REQUEST';
export const DELETE_TRANSACTION_CANCEL = 'DELETE_TRANSACTION_CANCEL';
export const DELETE_TRANSACTION_APPROVE = 'DELETE_TRANSACTION_APPROVE';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAILURE = 'DELETE_TRANSACTION_FAILURE';

export const TRANSACTION_DIALOG_OPEN = 'TRANSACTION_DIALOG_OPEN';
export const TRANSACTION_DIALOG_CLOSE = 'TRANSACTION_DIALOG_CLOSE';
